src/Entity/Article.php
<?php

namespace App\Entity;

use App\Service\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @UniqueEntity("title", message="Ce titre existe déjà")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champ ne peut pas rester vide")
     * @Assert\Length(max=255, maxMessage="Le titre est trop long")
     */

    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Ce champ ne peut pas rester vide")
     * @Assert\Regex(
     *     pattern="[digital]",
     *     match=false,
     *     message="en français, il faut dire numérique")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="articles")
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="favorites")
     */
    private $user_favorite;


    public function __toString()
    {

        return $this->title;
    }

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->user_favorite = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /*  public function getString(): ?string
      {
          return $this->string();
      }

      public function setString(string $string): self
      {
          $res = $this->string();

          return $res;
      } */

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUrl(): string
    {
        return preg_replace('/ /', '-', strtolower($this->getTitle()));

    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addArticle($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removeArticle($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getUserFavorite(): ?User
    {
        return $this->user_favorite;
    }

    public function setUserFavorite(?User $user_favorite): self
    {
        $this->user_favorite = $user_favorite;

        return $this;
    }

    public function addUserFavorite(User $userFavorite): self
    {
        if (!$this->user_favorite->contains($userFavorite)) {
            $this->user_favorite[] = $userFavorite;
            $userFavorite->addFavorite($this);
        }

        return $this;
    }

    public function removeUserFavorite(User $userFavorite): self
    {
        if ($this->user_favorite->contains($userFavorite)) {
            $this->user_favorite->removeElement($userFavorite);
            $userFavorite->removeFavorite($this);
        }

        return $this;
    }
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TagRepository")
 */
class Tag
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Article", inversedBy="tags")
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
        }

        return $this;
    }
}

src/Form/TagType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('articles',EntityType::class, [
                'class' => Article::class,
                'choice_label' => 'title',
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
        ]);
    }
}

src/Controller/TagController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Form\TagType;
use App\Repository\TagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route({"fr": "/tags",
 *     "en": "/tags",
 *     "es": "/tags"})
 */
class TagController extends AbstractController
{
    /**
     * @Route("/", name="tag_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(TagRepository $tagRepository): Response
    {
        return $this->render('tag/index.html.twig', [
            'tags' => $tagRepository->findAll(),
        ]);
    }


    /**
     * @Route({"fr": "/nouveau",
     *     "en": "/new",
     *     "es": "/crear"}, name="tag_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tag = new Tag();
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tag);
            $entityManager->flush();
            $this->addFlash('success', 'Un nouveau tag a été ajouté');

            return $this->redirectToRoute('tag_index');
        }

        return $this->render('tag/new.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{name}", name="tag_show", methods={"GET"})
     */
    public function show(Tag $tag): Response
    {
        $articles = $tag->getArticles();


        return $this->render('tag/show.html.twig', [
            'tag' => $tag,
            'articles' => $articles
        ]);
    }

    /**
     * @Route({"fr": "/{id}/modifier",
     *     "en": "/{id}/edit",
     *     "es": "/{id}/modificar"}, name="tag_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tag $tag): Response
    {
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Le tag a été modifié');

            return $this->redirectToRoute('tag_index', [
                'id' => $tag->getId(),
            ]);
        }

        return $this->render('tag/edit.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tag_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tag $tag): Response
    {
        if ($this->isCsrfTokenValid('delete' . $tag->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tag);
            $entityManager->flush();

            $this->addFlash('danger', 'Le tag a bien été supprimé');
        }

        return $this->redirectToRoute('tag_index');
    }
}

templates/tag/_delete_form.html.twig
<form method="post" action="{{ path('tag_delete', {'id': tag.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tag.id) }}">
    <button class="btn btn-primary">Delete</button>
</form>

templates/tag/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tag/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tag{% endblock %}

{% block body %}
    <h1>Edit Tag</h1>

    {{ include('tag/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('tag_index') }}">back to list</a>

    {{ include('tag/_delete_form.html.twig') }}
{% endblock %}

templates/tag/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tag index{% endblock %}

{% block body %}
    <h1>Tag index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tag in tags %}
            <tr>
                <td>{{ tag.id }}</td>
                <td>{{ tag.name }}</td>
                <td>
                    <a href="{{ path('tag_show', {'name': tag.name}) }}">show</a>
                    <a href="{{ path('tag_edit', {'id': tag.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('tag_new') }}">Create new</a>
{% endblock %}

templates/tag/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tag{% endblock %}

{% block body %}
    <h1>Create new Tag</h1>

    {{ include('tag/_form.html.twig') }}

    <a href="{{ path('tag_index') }}">back to list</a>
{% endblock %}

templates/tag/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tag{% endblock %}

{% block body %}
    <h1>Tag</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ tag.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ tag.name }}</td>
        </tr>


        </tbody>
    </table>

    <h2>Liste des articles</h2>
    {% for article in articles %}
        <div>
        {{ article.title }}

        <a href="{{ path('blog_article',{'slug': article.url, 'id': article.id}) }}">Go</a>
    {% endfor %}
    </div>
<br>
    <div>
        <a href="{{ path('tag_index') }}">back to list</a>

        <a class="" href="{{ path('tag_edit', {'id': tag.id}) }}">edit</a>

        {{ include('tag/_delete_form.html.twig') }}

    </div>

{% endblock %}